[workspace]
resolver = "2"
members = [
    "proto2",
    "client",
    "proto-gen",
    "server"
, "struct_accessor_macro"]
default-members = [
    "proto2",
    "client",
    "proto-gen",
    "server"
]
